### ISSUE TITLE
General Notes

### ISSUE THREAD

**Issue by alidah0** [GSG-G9/food-recipes-with-healthy-notes#30]
You did great job guys, I just wanna add an extra basic note.

- Use Eslint and also you should write your workspace VS code settings, It will help you as a team to work with the same environment, and will save you more time.
 you can customize your workspace setting, like this for example

```js
{
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
    "editor.formatOnSave": false,
    "editor.tabSize": 2,
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    }
}
```
- remove all `console.log` statement and unused code lines like:
https://github.com/GSG-G9/food-recipes-with-healthy-notes/blob/e508897bb77f4e3ffbe804b75f0ee316c06872e9/public/js/dom.js#L6 
Eslint would easily detect these silly bugs.

**Comment by hassanelnajjar** [comment]
Thx ali -we really need this settings in our project
